apiVersion: v1
kind: Service
metadata:
  name: ketran-webapp-service
spec:
  selector:
    app: ketran
    role: webapp
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
