apiVersion: v1
kind: Service
metadata:
  name: ketran-webapp-service
spec:
  selector:
    app: ketran
    role: webapp
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
