apiVersion: apps/v1
kind: Deployment
metadata:
  name: ketran-webapp-deployment
  labels:
    app: ketran
    role: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ketran
      role: webapp
  template:
    metadata:
      labels:
        app: ketran
        role: webapp
    spec:
      containers:
      - image: hojarasca/ketran-webapp:latest
        imagePullPolicy: Always
        name: ketran-webapp
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        metadata:
        ports:
          - containerPort: 3000
            name: http
            protocol: TCP