apiVersion: v1
kind: Pod
metadata:
  name: ketran-webapp
spec:
  containers:
    - image: hojarasca/ketran-webapp:latest
      name: ketran-webapp
      livenessProbe:
        httpGet:
          path: /
          port: 3000
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 3000
          name: http
          protocol: TCP